"""Generating and removing the shim executables.

A shim is a two-line launcher that sets one environment variable and execs the
real entry point. It is deliberately dumb: all logic lives in Python, so
upgrading the tool upgrades every shim without regenerating them.

Argument fidelity is the thing to get right, and it differs by platform:

  POSIX  "$@" preserves the argument vector exactly, including empty strings
         and embedded spaces, and `exec` replaces the shell so no extra
         process sits between the caller and the agent.

  Windows  %* re-expands the raw command line and Python re-parses it with the
         standard CommandLineToArgvW rules. That is ONE parse by the same
         parser every native program uses, so it matches what the real binary
         would have seen.
"""

from __future__ import annotations

import os
import shutil
import stat
import sys
from dataclasses import dataclass
from pathlib import Path

from . import paths
from .resolve import MARKER

WINDOWS = os.name == "nt"


@dataclass
class ShimResult:
    agent: str
    path: Path
    action: str  # created | updated | unchanged | skipped
    detail: str = ""


def entry_point() -> str:
    """Absolute path to the installed `tether-shim` launcher.

    Resolved once at install time and baked into the shim, so the shim does not
    depend on PATH at run time - which matters because the shim itself is on
    PATH and we are trying very hard not to re-enter it.
    """
    override = os.environ.get("TETHER_SHIM_ENTRY")
    if override:
        return override
    found = shutil.which("tether-shim")
    if found:
        return found
    # Running from a source checkout: fall back to the interpreter.
    return f'"{sys.executable}" -m tether.shim'


def _posix_body(agent: str, entry: str) -> str:
    quoted = entry if entry.startswith('"') else f'"{entry}"'
    return f"""#!/bin/sh
# {MARKER} - generated by agent-tether, safe to delete
# routes "{agent}" through a durable zellij session
TETHER_SHIM_AGENT={agent}
TETHER_SHIM_PATH="$0"
export TETHER_SHIM_AGENT TETHER_SHIM_PATH
exec {quoted} "$@"
"""


def _windows_body(agent: str, entry: str) -> str:
    quoted = entry if entry.startswith('"') else f'"{entry}"'
    return "\r\n".join(
        [
            "@echo off",
            f":: {MARKER} - generated by agent-tether, safe to delete",
            f':: routes "{agent}" through a durable zellij session',
            "setlocal",
            f'set "TETHER_SHIM_AGENT={agent}"',
            'set "TETHER_SHIM_PATH=%~f0"',
            f"{quoted} %*",
            "exit /b %ERRORLEVEL%",
            "",
        ]
    )


def shim_path(agent: str, directory: Path | None = None) -> Path:
    directory = directory or paths.bin_dir()
    return directory / (f"{agent}.cmd" if WINDOWS else agent)


def is_shim(path: Path) -> bool:
    try:
        if path.stat().st_size > 64 * 1024:
            return False
        with path.open("rb") as fh:
            return MARKER.encode() in fh.read(4096)
    except OSError:
        return False


def install(agent: str, directory: Path | None = None, entry: str | None = None) -> ShimResult:
    directory = directory or paths.bin_dir()
    directory.mkdir(parents=True, exist_ok=True)
    target = shim_path(agent, directory)
    entry = entry or entry_point()
    body = _windows_body(agent, entry) if WINDOWS else _posix_body(agent, entry)

    if target.exists() and not is_shim(target):
        return ShimResult(agent, target, "skipped", "a file that is not ours already exists there")

    # Compare BYTES. read_text() translates CRLF to LF on Windows, so a text
    # comparison against a CRLF body never matches and every reinstall would
    # report "updated" - harmless but a lie, and it hides real changes.
    existing = target.read_bytes() if target.exists() else None
    if existing is not None and existing == body.encode("utf-8"):
        return ShimResult(agent, target, "unchanged")

    target.write_text(body, encoding="utf-8", newline="")
    if not WINDOWS:
        mode = target.stat().st_mode
        target.chmod(mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    return ShimResult(agent, target, "updated" if existing else "created")


def uninstall(agent: str, directory: Path | None = None) -> ShimResult:
    target = shim_path(agent, directory)
    if not target.exists():
        return ShimResult(agent, target, "unchanged", "not present")
    if not is_shim(target):
        # Never delete a file we did not create.
        return ShimResult(agent, target, "skipped", "not an agent-tether shim; left alone")
    target.unlink()
    return ShimResult(agent, target, "removed")


def installed(directory: Path | None = None) -> list[str]:
    directory = directory or paths.bin_dir()
    if not directory.is_dir():
        return []
    out = []
    for path in sorted(directory.iterdir()):
        if path.is_file() and is_shim(path):
            out.append(path.stem if WINDOWS else path.name)
    return out


def path_entries() -> list[str]:
    return [p for p in os.environ.get("PATH", "").split(os.pathsep) if p]


def on_path(directory: Path | None = None) -> bool:
    directory = directory or paths.bin_dir()
    try:
        target = directory.resolve()
    except OSError:
        target = directory
    for entry in path_entries():
        try:
            if Path(entry).expanduser().resolve() == target:
                return True
        except OSError:
            continue
    return False


def shadows_correctly(agent: str, directory: Path | None = None) -> tuple[bool, str]:
    """Does our shim actually win for this name?

    Checking `which` is the only honest test. A shim can be present, on PATH,
    and still lose - most commonly because the real binary's directory comes
    first, or because it sits in the SAME directory and PATHEXT prefers .exe.
    """
    resolved = shutil.which(agent)
    if not resolved:
        return False, "not found on PATH at all"
    p = Path(resolved)
    if is_shim(p):
        return True, str(p)
    return False, f"resolves to {p} (not our shim)"


def path_hint(directory: Path | None = None) -> str:
    directory = directory or paths.bin_dir()
    if WINDOWS:
        return (
            f'setx PATH "{directory};%PATH%"    '
            "(then open a NEW terminal; setx affects new processes only)"
        )
    return f'export PATH="{directory}:$PATH"    # add to ~/.bashrc, ~/.zshrc or ~/.profile'
