"""Generating and removing the shim executables.

A shim is a two-line launcher that sets one environment variable and execs the
real entry point. It is deliberately dumb: all logic lives in Python, so
upgrading the tool upgrades every shim without regenerating them.

Argument fidelity is the thing to get right, and it differs by platform:

  POSIX  "$@" preserves the argument vector exactly, including empty strings
         and embedded spaces, and `exec` replaces the shell so no extra
         process sits between the caller and the agent.

  Windows  %* re-expands the raw command line and Python re-parses it with the
         standard CommandLineToArgvW rules. That is ONE parse by the same
         parser every native program uses, so it matches what the real binary
         would have seen.
"""

from __future__ import annotations

import os
import shutil
import stat
import sys
from dataclasses import dataclass
from pathlib import Path

from . import paths
from .resolve import MARKER, _is_our_shim, launcher_exe

WINDOWS = os.name == "nt"


@dataclass
class ShimResult:
    agent: str
    path: Path
    action: str  # created | updated | unchanged | skipped
    detail: str = ""


def entry_point() -> str:
    """Absolute path to the installed `tether-shim` launcher.

    Resolved once at install time and baked into the shim, so the shim does not
    depend on PATH at run time - which matters because the shim itself is on
    PATH and we are trying very hard not to re-enter it.
    """
    override = os.environ.get("TETHER_SHIM_ENTRY")
    if override:
        return override
    found = shutil.which("tether-shim")
    if found:
        return found
    # Running from a source checkout: fall back to the interpreter.
    return f'"{sys.executable}" -m tether.shim'


def _posix_body(agent: str, entry: str) -> str:
    quoted = entry if entry.startswith('"') else f'"{entry}"'
    return f"""#!/bin/sh
# {MARKER} - generated by agent-tether, safe to delete
# routes "{agent}" through a durable zellij session
TETHER_SHIM_AGENT={agent}
TETHER_SHIM_PATH="$0"
export TETHER_SHIM_AGENT TETHER_SHIM_PATH
exec {quoted} "$@"
"""


def _windows_body(agent: str, entry: str) -> str:
    quoted = entry if entry.startswith('"') else f'"{entry}"'
    return "\r\n".join(
        [
            "@echo off",
            f":: {MARKER} - generated by agent-tether, safe to delete",
            f':: routes "{agent}" through a durable zellij session',
            "setlocal",
            f'set "TETHER_SHIM_AGENT={agent}"',
            'set "TETHER_SHIM_PATH=%~f0"',
            f"{quoted} %*",
            "exit /b %ERRORLEVEL%",
            "",
        ]
    )


def shim_path(agent: str, directory: Path | None = None) -> Path:
    directory = directory or paths.bin_dir()
    return directory / (f"{agent}.cmd" if WINDOWS else agent)


def is_shim(path: Path) -> bool:
    """Is this file one of ours?

    Delegates to resolve so generation and RESOLUTION can never disagree about
    what counts as our shim - a disagreement there means infinite recursion.
    """
    return _is_our_shim(path)


def _write_if_changed(target: Path, body: str) -> None:
    existing = target.read_bytes() if target.exists() else None
    if existing != body.encode("utf-8"):
        target.write_text(body, encoding="utf-8", newline="")


def install(agent: str, directory: Path | None = None, entry: str | None = None) -> ShimResult:
    directory = directory or paths.bin_dir()
    directory.mkdir(parents=True, exist_ok=True)
    target = shim_path(agent, directory)
    entry = entry or entry_point()

    if WINDOWS:
        exe_source = launcher_exe()
        exe_target = directory / f"{agent}.exe"
        if exe_source is not None:
            # Guard BOTH artifacts before writing either, so a foreign file at
            # one path is never half-shadowed by us writing the other.
            for candidate in (exe_target, target):
                if candidate.exists() and not is_shim(candidate):
                    return ShimResult(
                        agent, candidate, "skipped", "a file that is not ours already exists there"
                    )
            existing = exe_target.read_bytes() if exe_target.exists() else None
            payload = exe_source.read_bytes()
            action = "unchanged" if existing == payload else ("updated" if existing else "created")
            if action != "unchanged":
                shutil.copyfile(exe_source, exe_target)
            # The .cmd is written too, as inert insurance: within one directory
            # PATHEXT resolves .EXE before .CMD, so the exe still wins, but a
            # shell-only caller on a machine missing the exe still works.
            _write_if_changed(target, _windows_body(agent, entry))
            return ShimResult(agent, exe_target, action)

    body = _windows_body(agent, entry) if WINDOWS else _posix_body(agent, entry)

    if target.exists() and not is_shim(target):
        return ShimResult(agent, target, "skipped", "a file that is not ours already exists there")

    # Compare BYTES. read_text() translates CRLF to LF on Windows, so a text
    # comparison against a CRLF body never matches and every reinstall would
    # report "updated" - harmless but a lie, and it hides real changes.
    existing = target.read_bytes() if target.exists() else None
    if existing is not None and existing == body.encode("utf-8"):
        return ShimResult(agent, target, "unchanged")

    target.write_text(body, encoding="utf-8", newline="")
    if not WINDOWS:
        mode = target.stat().st_mode
        target.chmod(mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    return ShimResult(agent, target, "updated" if existing else "created")


def uninstall(agent: str, directory: Path | None = None) -> ShimResult:
    directory = directory or paths.bin_dir()
    targets = [shim_path(agent, directory)]
    if WINDOWS:
        targets.insert(0, directory / f"{agent}.exe")

    present = [t for t in targets if t.exists()]
    if not present:
        return ShimResult(agent, targets[0], "unchanged", "not present")

    foreign = [t for t in present if not is_shim(t)]
    if foreign:
        # Never delete a file we did not create.
        return ShimResult(agent, foreign[0], "skipped", "not an agent-tether shim; left alone")

    for t in present:
        t.unlink()
    return ShimResult(agent, present[0], "removed")


def installed(directory: Path | None = None) -> list[str]:
    directory = directory or paths.bin_dir()
    if not directory.is_dir():
        return []
    # Deduped: on Windows one agent has both a .exe and a .cmd.
    out: set[str] = set()
    for path in sorted(directory.iterdir()):
        if not path.is_file() or not is_shim(path):
            continue
        out.add(path.stem if path.suffix else path.name)
    return sorted(out)


def path_entries() -> list[str]:
    return [p for p in os.environ.get("PATH", "").split(os.pathsep) if p]


def on_path(directory: Path | None = None) -> bool:
    directory = directory or paths.bin_dir()
    try:
        target = directory.resolve()
    except OSError:
        target = directory
    for entry in path_entries():
        try:
            if Path(entry).expanduser().resolve() == target:
                return True
        except OSError:
            continue
    return False


def shadows_correctly(agent: str, directory: Path | None = None) -> tuple[bool, str]:
    """Does our shim actually win for this name?

    Checking `which` is the only honest test. A shim can be present, on PATH,
    and still lose - most commonly because the real binary's directory comes
    first, or because it sits in the SAME directory and PATHEXT prefers .exe.
    """
    resolved = shutil.which(agent)
    if not resolved:
        return False, "not found on PATH at all"
    p = Path(resolved)
    if is_shim(p):
        return True, str(p)
    return False, f"resolves to {p} (not our shim)"


def path_hint(directory: Path | None = None) -> str:
    directory = directory or paths.bin_dir()
    if WINDOWS:
        return (
            f'setx PATH "{directory};%PATH%"    '
            "(then open a NEW terminal; setx affects new processes only)"
        )
    return f'export PATH="{directory}:$PATH"    # add to ~/.bashrc, ~/.zshrc or ~/.profile'
